/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ca.objectobject.hexlr

import ca.objectobject.hexlr.eval.iotas.BooleanIota
import ca.objectobject.hexlr.eval.iotas.Iota
import ca.objectobject.hexlr.eval.iotas.NumberIota
import ca.objectobject.hexlr.eval.iotas.VectorIota
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import kotlin.test.assertEquals

class HexlrTest {
    @ParameterizedTest
    @MethodSource("getData")
    fun programProducesExpectedStack(program: String, want: List<Iota>) {
        val runtime = execute(program.trimIndent())
        assertEquals(want.asReversed(), runtime.stack.toList())
    }

    companion object {
        @JvmStatic
        fun getData() = listOf(
            "" to listOf(),
            "Numerical Reflection: 0" to listOf(NumberIota(0)),
            "Numerical Reflection: 1" to listOf(NumberIota(1)),
            "Numerical Reflection: -2.5" to listOf(NumberIota(-2.5)),
            "Numerical Reflection: 1e2" to listOf(NumberIota(100)),
            """
                Numerical Reflection: 0
                Numerical Reflection: 1
            """ to listOf(
                NumberIota(1),
                NumberIota(0),
            ),
            """
                Numerical Reflection: 1
                Numerical Reflection: 2
                Additive Distillation
            """ to listOf(NumberIota(3)),
            """
                Numerical Reflection: 1
                Numerical Reflection: 2
                Subtractive Distillation
            """ to listOf(NumberIota(-1)),
            """
                Numerical Reflection: 2
                Numerical Reflection: 3
                Multiplicative Distillation
            """ to listOf(NumberIota(6)),
            """
                Numerical Reflection: 1
                Numerical Reflection: 2
                Division Distillation
            """ to listOf(NumberIota(0.5)),
            """
                Numerical Reflection: 0
                Numerical Reflection: 1
                Numerical Reflection: 2
                Vector Exaltation
            """ to listOf(VectorIota(0, 1, 2)),
            "True Reflection" to listOf(BooleanIota(true)),
            "False Reflection" to listOf(BooleanIota(false)),
            """
                True Reflection
                Numerical Reflection: 1
                Numerical Reflection: 2
                Augur's Exaltation
            """ to listOf(NumberIota(1)),
            """
                False Reflection
                Numerical Reflection: 1
                Numerical Reflection: 2
                Augur's Exaltation
            """ to listOf(NumberIota(2)),
        ).map { Arguments.of(it.first, it.second) }
    }
}
